repos:
  - repo: local
    hooks:
      - id: format
        name: Test format
        entry: make test_format
        language: system
        pass_filenames: false
      - id: validation
        name: Test validation
        entry: make test_validation
        language: system
        pass_filenames: false
      - id: documentation
        name: Test documentation
        entry: make test_documentation
        language: system
        pass_filenames: false
      - id: lint
        name: Test lint
        entry: make test_tflint
        language: system
        pass_filenames: false
      - id: security
        name: Test security
        entry: make test_security
        language: system
        pass_filenames: false
