name: Test Build Template

on:
  push:
  pull_request:

jobs:
  rebuild-templates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: "Install Cookiecutter"
        run: pip install --user cookiecutter

      - name: "Build Template"
        run: make test
